language: php
sudo: false
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

addons:
  code_climate:
    repo_token: 41727c20302fa699430a7aa0e06ef4d2cc00aeb25df3673f4165df75b6efccbc

before_script:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/coverage-clover.xml

after_success:
  - vendor/bin/test-reporter --coverage-report ./tests/logs/coverage-clover.xml
  - vendor/bin/coveralls -v