language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

env:
  - REGENERATE=false

matrix:
  include:
    - php: 5.5
      env: PHP_VERSION="5.5"
    - php: 5.6
      env: PHP_VERSION="5.6"
    - php: 7.0
      env: PHP_VERSION="7.0"
    - php: 7.1
      env: PHP_VERSION="7.1"
    - php: 7.2
      env: PHP_VERSION="7.2"
    - php: 7.3
      env: PHP_VERSION="7.3"
    - php: 7.4
      env:
        - PHP_VERSION="7.4"
        - REGENERATE=true

addons:
  code_climate:
    repo_token: 41727c20302fa699430a7aa0e06ef4d2cc00aeb25df3673f4165df75b6efccbc

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update

script:
  - if $REGENERATE; then php scraping/src/generator.php &>> tests/logs/generator.log; fi
  - if $REGENERATE; then sh scraping/sync.sh &>> tests/logs/sync.log; fi
  - if [ `echo "$PHP_VERSION < 7.3" | bc` == 1 ]; then vendor/bin/phpunit --coverage-clover tests/logs/coverage-clover.xml; fi
  - if [ `echo "$PHP_VERSION >= 7.3" | bc` == 1 ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover tests/logs/coverage-clover.xml; fi

after_success:
  - vendor/bin/test-reporter --coverage-report tests/logs/coverage-clover.xml
  - vendor/bin/coveralls -v

after_script:
  - if [ -f tests/logs/generator.log ]; then cat tests/logs/generator.log; fi
  - if [ -f tests/logs/sync.log ]; then cat tests/logs/sync.log; fi