language: php
sudo: false
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/coverage-clover.xml