language: php
sudo: false
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - REGENERATE=false

matrix:
  include:
    - php: 7.2
      env: REGENERATE=true

addons:
  code_climate:
    repo_token: 41727c20302fa699430a7aa0e06ef4d2cc00aeb25df3673f4165df75b6efccbc

before_script:
  - travis_retry composer install

script:
  - if $REGENERATE; then php scraping/src/generator.php &>> tests/logs/generator.log; fi
  - if $REGENERATE; then sh scraping/sync.sh &>> tests/logs/sync.log; fi
  - vendor/bin/phpunit --coverage-clover tests/logs/coverage-clover.xml

after_success:
  - vendor/bin/test-reporter --coverage-report tests/logs/coverage-clover.xml
  - vendor/bin/coveralls -v

after_script:
  - if [ -f tests/logs/generator.log ]; then cat tests/logs/generator.log; fi
  - if [ -f tests/logs/sync.log ]; then cat tests/logs/sync.log; fi